project:
  type: book
  output-dir: docs

book:
  title: "biol827-graduate_statistics"
  author: "Dr. Jacob C. Cooper"
  date: "9/22/2024"
  chapters:
    - index.qmd
    - hwe.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

